spring:
    datasource:
        url: jdbc:mysql://db:3306/testdb
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: update